In [461]:
# Importing the libraries
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from matplotlib.colors import ListedColormap


In [ ]:
# Importing the dataset

In [462]:
file=pd.read_excel("C:/Users/HOME/Desktop/data 2.xlsx")

In [463]:
file

Brand     Price       Body  Mileage  EngineV EngineType  \
0               BMW    4200.0      sedan      277      2.0     Petrol   
1     Mercedes-Benz    7900.0        van      427      2.9     Diesel   
2     Mercedes-Benz   13300.0      sedan      358      5.0        Gas   
3              Audi   23000.0  crossover      240      4.2     Petrol   
4            Toyota   18300.0  crossover      120      2.0     Petrol   
...             ...       ...        ...      ...      ...        ...   
4340  Mercedes-Benz  125000.0      sedan        9      3.0     Diesel   
4341            BMW    6500.0      sedan        1      3.5     Petrol   
4342            BMW    8000.0      sedan      194      2.0     Petrol   
4343         Toyota   14200.0      sedan       31      NaN     Petrol   
4344     Volkswagen   13500.0        van      124      2.0     Diesel   

     Registration  Year              Model  
0             yes  1991                320  
1             yes  1999       Sprinter 212  
2             yes  2003              S 500  
3             yes  2007                 Q7  
4             yes  2011              Rav 4  
...           ...   ...                ...  
4340          yes  2014              S 350  
4341          yes  1999                535  
4342          yes  1985                520  
4343          yes  2014            Corolla  
4344          yes  2013  T5 (Transporter)   

[4345 rows x 9 columns]

In [464]:
db=file.isnull().sum()

In [465]:
db

Brand             0
Price             0
Body              0
Mileage           0
EngineV         150
EngineType        0
Registration      0
Year              0
Model             0
dtype: int64

In [466]:
file.fillna(file.mean())

C:\Users\HOME\AppData\Local\Temp\ipykernel_19400\1606865399.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  file.fillna(file.mean())


Brand     Price       Body  Mileage   EngineV EngineType  \
0               BMW    4200.0      sedan      277  2.000000     Petrol   
1     Mercedes-Benz    7900.0        van      427  2.900000     Diesel   
2     Mercedes-Benz   13300.0      sedan      358  5.000000        Gas   
3              Audi   23000.0  crossover      240  4.200000     Petrol   
4            Toyota   18300.0  crossover      120  2.000000     Petrol   
...             ...       ...        ...      ...       ...        ...   
4340  Mercedes-Benz  125000.0      sedan        9  3.000000     Diesel   
4341            BMW    6500.0      sedan        1  3.500000     Petrol   
4342            BMW    8000.0      sedan      194  2.000000     Petrol   
4343         Toyota   14200.0      sedan       31  2.790734     Petrol   
4344     Volkswagen   13500.0        van      124  2.000000     Diesel   

     Registration  Year              Model  
0             yes  1991                320  
1             yes  1999       Sprinter 212  
2             yes  2003              S 500  
3             yes  2007                 Q7  
4             yes  2011              Rav 4  
...           ...   ...                ...  
4340          yes  2014              S 350  
4341          yes  1999                535  
4342          yes  1985                520  
4343          yes  2014            Corolla  
4344          yes  2013  T5 (Transporter)   

[4345 rows x 9 columns]

In [467]:
db.isnull().sum()

0

In [468]:
v=['Registration','Year']

In [469]:
newfile=file.drop(v,axis=1)

In [470]:
newfile

Brand     Price       Body  Mileage  EngineV EngineType  \
0               BMW    4200.0      sedan      277      2.0     Petrol   
1     Mercedes-Benz    7900.0        van      427      2.9     Diesel   
2     Mercedes-Benz   13300.0      sedan      358      5.0        Gas   
3              Audi   23000.0  crossover      240      4.2     Petrol   
4            Toyota   18300.0  crossover      120      2.0     Petrol   
...             ...       ...        ...      ...      ...        ...   
4340  Mercedes-Benz  125000.0      sedan        9      3.0     Diesel   
4341            BMW    6500.0      sedan        1      3.5     Petrol   
4342            BMW    8000.0      sedan      194      2.0     Petrol   
4343         Toyota   14200.0      sedan       31      NaN     Petrol   
4344     Volkswagen   13500.0        van      124      2.0     Diesel   

                  Model  
0                   320  
1          Sprinter 212  
2                 S 500  
3                    Q7  
4                 Rav 4  
...                 ...  
4340              S 350  
4341                535  
4342                520  
4343            Corolla  
4344  T5 (Transporter)   

[4345 rows x 7 columns]

In [471]:
newfile.Brand= newfile.Brand.replace("BMW",0)
newfile.Brand= newfile.Brand.replace("Mercedes-Benz",1)
newfile.Brand= newfile.Brand.replace("Audi",3)
newfile.Brand= newfile.Brand.replace("Toyota",4)
newfile.Brand= newfile.Brand.replace("Volkswagen",3)
newfile.Brand= newfile.Brand.replace("Mitsubishi",4)
newfile.Brand= newfile.Brand.replace("Renault",5)

In [472]:
newfile.engine= newfile.EngineType.replace("Petrol",4)
newfile.engine= newfile.EngineType.replace("Diesel",5)
newfile.engine= newfile.EngineType.replace("Gas",6)

C:\Users\HOME\AppData\Local\Temp\ipykernel_19400\3680532031.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  newfile.engine= newfile.EngineType.replace("Petrol",4)


In [511]:
from pandas.core.arrays import boolean

In [513]:
newfile['Price']=newfile['Price'].astype(bool)

In [515]:
newfile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4345 entries, 0 to 4344
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Brand       4345 non-null   int64  
 1   Price       4345 non-null   bool   
 2   Body        4345 non-null   object 
 3   Mileage     4345 non-null   int64  
 4   EngineV     4195 non-null   float64
 5   EngineType  4345 non-null   object 
 6   Model       4345 non-null   object 
dtypes: bool(1), float64(1), int64(2), object(3)
memory usage: 208.0+ KB


In [516]:
newfile.isnull().sum()

Brand           0
Price           0
Body            0
Mileage         0
EngineV       150
EngineType      0
Model           0
dtype: int64

In [517]:
file=newfile.fillna(newfile.mean())

C:\Users\HOME\AppData\Local\Temp\ipykernel_19400\3207493841.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  file=newfile.fillna(newfile.mean())


In [518]:
file.isnull().sum()

Brand         0
Price         0
Body          0
Mileage       0
EngineV       0
EngineType    0
Model         0
dtype: int64

In [519]:
a=["Model","Body","EngineV"]

In [520]:
dataset=file.drop(a,axis=1)

In [521]:
dataset

Brand  Price  Mileage EngineType
0         0   True      277     Petrol
1         1   True      427     Diesel
2         1   True      358        Gas
3         3   True      240     Petrol
4         4   True      120     Petrol
...     ...    ...      ...        ...
4340      1   True        9     Diesel
4341      0   True        1     Petrol
4342      0   True      194     Petrol
4343      4   True       31     Petrol
4344      3   True      124     Diesel

[4345 rows x 4 columns]

In [522]:
v=dataset.fillna(dataset.mean())

C:\Users\HOME\AppData\Local\Temp\ipykernel_19400\4157150153.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  v=dataset.fillna(dataset.mean())


In [523]:
v.isnull().sum()

Brand         0
Price         0
Mileage       0
EngineType    0
dtype: int64

In [524]:
X=v.iloc[:,-3].values
Y=v.iloc[:,1].values

In [525]:
X

array([ True,  True,  True, ...,  True,  True,  True])

In [526]:
X=X.reshape(-1, 1)

In [527]:
X

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [528]:
array=np.array([45., 200., 148., ..., 153., 980., 148.])

In [529]:

reshaped_array = array.reshape(1,-1)

In [530]:
Y

array([ True,  True,  True, ...,  True,  True,  True])

In [ ]:
# Splitting the dataset into the Training set and Test set

In [531]:
from sklearn.model_selection import train_test_split


In [532]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.05,random_state=0)

In [533]:
print(X_train)

[[ True]
 [ True]
 [ True]
 ...
 [ True]
 [ True]
 [ True]]


In [534]:
print(Y_train)

[ True  True  True ...  True  True  True]


In [535]:
print(X_test)

[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 

In [536]:
array.reshape(1,-1)

array([[45.0, 200.0, 148.0, Ellipsis, 153.0, 980.0, 148.0]], dtype=object)

In [537]:
print(Y_test)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [ ]:
 # Feature Scaling

In [538]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()


In [539]:
sc

StandardScaler()

In [540]:
X_scaled=sc.fit_transform(X)

In [541]:
X_train=sc.fit_transform(X_train)

In [542]:
X_train

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [543]:
X_test=sc.transform(X_test)

In [544]:
X_test

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [545]:
print(X_train)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [546]:
print(X_test)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [ ]:
# Training the Decision Tree Classification model on the Training set

In [547]:

from sklearn.tree import DecisionTreeClassifier

In [548]:
classifier=DecisionTreeClassifier(criterion = 'entropy', random_state = 0)

In [ ]:
# Predicting a new result

In [549]:
from sklearn.tree import DecisionTreeRegressor

In [550]:
classifier.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [551]:
print(classifier.predict(sc.transform([[277]])))


[ True]


In [ ]:
# Predicting the Test set results

In [552]:
y_pred=classifier.predict(X_test)

In [553]:
y_pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [554]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))


[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  T

In [ ]:
# Making the Confusion Matrix

In [555]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [556]:
cm=confusion_matrix(Y_test, y_pred)

In [557]:
cm

array([[218]], dtype=int64)

In [558]:
print(cm)

[[218]]


In [559]:
accuracy_score(Y_test, y_pred)


1.0

In [560]:
X_set, Y_set = sc.inverse_transform(X_train), Y_train

In [561]:
X_set, Y_set

(array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]]),
 array([ True,  True,  True, ...,  True,  True,  True]))

In [562]:
X1, X2=np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:,: 1].min() - 1000, stop = X_set[:,: 1].max() + 1000, step = 0.25))

In [563]:
X1,X2

(array([[-9.  , -8.75, -8.5 , ..., 10.25, 10.5 , 10.75],
        [-9.  , -8.75, -8.5 , ..., 10.25, 10.5 , 10.75],
        [-9.  , -8.75, -8.5 , ..., 10.25, 10.5 , 10.75],
        ...,
        [-9.  , -8.75, -8.5 , ..., 10.25, 10.5 , 10.75],
        [-9.  , -8.75, -8.5 , ..., 10.25, 10.5 , 10.75],
        [-9.  , -8.75, -8.5 , ..., 10.25, 10.5 , 10.75]]),
 array([[-999.  , -999.  , -999.  , ..., -999.  , -999.  , -999.  ],
        [-998.75, -998.75, -998.75, ..., -998.75, -998.75, -998.75],
        [-998.5 , -998.5 , -998.5 , ..., -998.5 , -998.5 , -998.5 ],
        ...,
        [1000.25, 1000.25, 1000.25, ..., 1000.25, 1000.25, 1000.25],
        [1000.5 , 1000.5 , 1000.5 , ..., 1000.5 , 1000.5 , 1000.5 ],
        [1000.75, 1000.75, 1000.75, ..., 1000.75, 1000.75, 1000.75]]))